spring.application.name=iHealth
server.port=8080

# ===============================
# AIVEN CLOUD MYSQL CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://mysql-250f1f6b-radoiaris14-6711.e.aivencloud.com:11343/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_OVCbchEFoL3EyM5TL-k
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIBERNATE & JPA CONFIGURATION
# ===============================
# Aceast? setare (update) asigur? crearea/actualizarea automat? a tabelelor din cod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# IOT / MQTT CONFIGURATION
# ===============================
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=spring-boot-server-ihealth