spring.application.name=iHealth
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/db_iHealth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PostgreSQL Cloud Configuration (Optional - For future use)
# spring.datasource.url=jdbc:postgresql://<IP_CLOUD>:5432/db_iHealth
# spring.datasource.username=<USER_CLOUD>
# spring.datasource.password=<PASSWORD_CLOUD>
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=spring-boot-server-ihealth